apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: example
  namespace: argo
spec:
  entrypoint: whalesay
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [cowsay]
      args: ["hello world"]
