apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: python-script-workflow
  namespcae: argo
spec:
  templates:
  - name: python-script
    script:
      image: python:3.9
      command: ["python"]
      source: |
        import os
        print("hello world python")
